apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: workload-ingress
 namespace: workload
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   #kubernetes.io/tls-acme: "true"
spec:
  #tls:
  #- hosts:
   # - workloads.openebs.io
    #secretName: workload-ingress
  rules:
  - host: workloads.openebs.io
    http:
      paths:
      - path: /
        backend:
          serviceName: www-workload-client-service
          servicePort: 80
